language: python
python:
  - "3.6"
before_script:
 - pip install pillow
 - git clone https://github.com/cc65/cc65.git
 - cd cc65
 - make >/dev/null || make -j2
 - make install PREFIX=~/.local
 - cd ..
script:
- make pently.nes
